In [ ]:
import pandas as pd

df = pd.read_csv('/Users/Di/Documents/Новая папка/Geodata/EDA/objects_registry.csv')

In [ ]:
df

,file_name,file_path,region,modality,class_raw,class_norm,geometry_type,object_id_in_file,part_id,area_m2,perimeter_m,centroid_x,centroid_y,minx,miny,maxx,maxy
0,Демидовка_Li_городища.geojson,/Volumes/Lexar/Датасет/004_ДЕМИДОВКА/06_Демидо...,Демидовка,Li,городища,gorodishcha,Polygon,0,0,11400.933031,399.755405,3.546142e+06,7.312747e+06,3.546063e+06,7.312691e+06,3.546213e+06,7.312795e+06
1,Демидовка_Li_городища.geojson,/Volumes/Lexar/Датасет/004_ДЕМИДОВКА/06_Демидо...,Демидовка,Li,городища,gorodishcha,Polygon,1,0,6293.645325,303.230307,3.546716e+06,7.311790e+06,3.546665e+06,7.311749e+06,3.546774e+06,7.311838e+06
2,Демидовка_SpOr_городища.geojson,/Volumes/Lexar/Датасет/004_ДЕМИДОВКА/06_Демидо...,Демидовка,SpOr,городища,gorodishcha,Polygon,0,0,15232.973669,478.167715,3.546135e+06,7.312756e+06,3.546043e+06,7.312692e+06,3.546219e+06,7.312807e+06
3,Лубно_Li_городища.geojson,/Volumes/Lexar/Датасет/005_ЛУБНО/06_Лубно_разм...,Лубно,Li,городища,gorodishcha,Polygon,0,0,15255.370401,484.793987,3.548270e+06,7.309928e+06,3.548185e+06,7.309850e+06,3.548353e+06,7.310005e+06
4,Лубно_Li_фортификации.geojson,/Volumes/Lexar/Датасет/005_ЛУБНО/06_Лубно_разм...,Лубно,Li,фортификации,fortifikatsii,Polygon,0,0,5701.103033,277.458269,3.548460e+06,7.309688e+06,3.548420e+06,7.309641e+06,3.548499e+06,7.309738e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4584,Семибратнее_Городище_уч3_MagGr_ObjectPoly.geojson,/Volumes/Lexar/Датасет/685_Семибратнее_Городищ...,Семибратнее_Городище_уч3,MagGr,ObjectPoly,object_poly,Polygon,13,0,18.078371,15.446638,3.824751e+05,4.999438e+06,3.824728e+05,4.999435e+06,3.824776e+05,4.999440e+06
4585,Семибратнее_Городище_уч3_MagGr_ObjectPoly.geojson,/Volumes/Lexar/Датасет/685_Семибратнее_Городищ...,Семибратнее_Городище_уч3,MagGr,ObjectPoly,object_poly,Polygon,14,0,163.118875,53.406292,3.824132e+05,4.999475e+06,3.824049e+05,4.999467e+06,3.824207e+05,4.999484e+06
4586,Семибратнее_Городище_уч3_MagGr_ObjectPoly.geojson,/Volumes/Lexar/Датасет/685_Семибратнее_Городищ...,Семибратнее_Городище_уч3,MagGr,ObjectPoly,object_poly,Polygon,15,0,46.778490,26.018880,3.823918e+05,4.999482e+06,3.823872e+05,4.999479e+06,3.823967e+05,4.999486e+06
4587,Семибратнее_Городище_уч3_MagGr_ObjectPoly.geojson,/Volumes/Lexar/Датасет/685_Семибратнее_Городищ...,Семибратнее_Городище_уч3,MagGr,ObjectPoly,object_poly,Polygon,16,0,28.221519,21.787707,3.823859e+05,4.999479e+06,3.823831e+05,4.999475e+06,3.823893e+05,4.999483e+06
4588,Семибратнее_Городище_уч3_MagGr_ObjectPoly.geojson,/Volumes/Lexar/Датасет/685_Семибратнее_Городищ...,Семибратнее_Городище_уч3,MagGr,ObjectPoly,object_poly,Polygon,17,0,301.127856,107.976705,3.824584e+05,4.999423e+06,3.824500e+05,4.999401e+06,3.824661e+05,4.999444e+06

In [ ]:
print("Size:", df.shape)

(4589, 17)

In [65]:
df.groupby("region").size().sort_values(ascending=False)

region
Тимерево                    885
Семибратнее_Городище_уч1    439
Семибратнее_Городище_уч3    405
Судбищи                     270
Семибратнее_Городище_уч2    216
                           ...
Руна                          1
Скупая_Полудань               1
Россошки                      1
Тоссор                        1
Шаты                          1
Length: 112, dtype: int64

In [51]:
df["modality"].value_counts()

modality
MagGr    1329
Ae       1274
SpOr      976
Li        934
Or         76
Name: count, dtype: int64

In [54]:
df["class_norm"].value_counts()

class_norm
kurgany_povrezhdennye    1822
finds_points             1278
kurgany_tselye            669
fortifikatsii             473
arkhitektury              218
gorodishcha                78
object_poly                51
Name: count, dtype: int64

In [53]:
pd.crosstab(df["modality"], df["class_norm"])

class_norm,arkhitektury,finds_points,fortifikatsii,gorodishcha,kurgany_povrezhdennye,kurgany_tselye,object_poly
modality,,,,,,,
Ae,16,0,243,11,638,366,0
Li,0,0,192,15,569,158,0
MagGr,0,1278,0,0,0,0,51
Or,70,0,2,4,0,0,0
SpOr,132,0,36,48,615,145,0

In [ ]:
df.groupby("region").agg({
    "file_name": "count",
    "class_norm": "nunique",
    "modality": "nunique"
}).sort_values("file_name", ascending=False)

                          file_name  class_norm  modality
region
Тимерево                        885           2         2
Семибратнее_Городище_уч1        439           2         1
Семибратнее_Городище_уч3        405           2         1
Судбищи                         270           3         2
Семибратнее_Городище_уч2        216           2         1
...                             ...         ...       ...
Руна                              1           1         1
Скупая_Полудань                   1           1         1
Россошки                          1           1         1
Тоссор                            1           1         1
Шаты                              1           1         1

[112 rows x 3 columns]

In [56]:
df.groupby("class_norm")["area_m2"].describe()

,count,mean,std,min,25%,50%,75%,max
class_norm,,,,,,,,
arkhitektury,218.0,936.129962,2620.365395,0.095957,36.212178,164.680737,438.901703,20117.377726
finds_points,1278.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
fortifikatsii,473.0,6040.804030,34183.610547,0.350684,298.937670,621.991442,2081.455840,648489.510022
gorodishcha,78.0,65082.520170,82010.194657,0.014685,13663.776072,24537.424959,92388.632296,428889.118169
kurgany_povrezhdennye,1822.0,2648.470724,15082.943316,24.307996,180.636051,342.195991,1314.060907,414454.223009
kurgany_tselye,669.0,1822.354609,5699.956049,26.550397,187.637491,381.095620,955.789617,80683.437019
object_poly,51.0,208.772820,359.991718,10.684334,23.398342,47.362643,179.581427,1624.967655

In [44]:
df["geometry_type"].value_counts()

geometry_type
Polygon    3311
Point      1278
Name: count, dtype: int64

In [67]:
KEEP_CLASSES = [
"kurgany_povrezhdennye",
"kurgany_tselye",
"fortifikatsii",
"arkhitektury",
"gorodishcha"
]

df_goal = df[df["class_norm"].isin(KEEP_CLASSES)]

In [68]:
df_goal

,file_name,file_path,region,modality,class_raw,class_norm,geometry_type,object_id_in_file,part_id,area_m2,perimeter_m,centroid_x,centroid_y,minx,miny,maxx,maxy
0,Демидовка_Li_городища.geojson,/Volumes/Lexar/Датасет/004_ДЕМИДОВКА/06_Демидо...,Демидовка,Li,городища,gorodishcha,Polygon,0,0,11400.933031,399.755405,3.546142e+06,7.312747e+06,3.546063e+06,7.312691e+06,3.546213e+06,7.312795e+06
1,Демидовка_Li_городища.geojson,/Volumes/Lexar/Датасет/004_ДЕМИДОВКА/06_Демидо...,Демидовка,Li,городища,gorodishcha,Polygon,1,0,6293.645325,303.230307,3.546716e+06,7.311790e+06,3.546665e+06,7.311749e+06,3.546774e+06,7.311838e+06
2,Демидовка_SpOr_городища.geojson,/Volumes/Lexar/Датасет/004_ДЕМИДОВКА/06_Демидо...,Демидовка,SpOr,городища,gorodishcha,Polygon,0,0,15232.973669,478.167715,3.546135e+06,7.312756e+06,3.546043e+06,7.312692e+06,3.546219e+06,7.312807e+06
3,Лубно_Li_городища.geojson,/Volumes/Lexar/Датасет/005_ЛУБНО/06_Лубно_разм...,Лубно,Li,городища,gorodishcha,Polygon,0,0,15255.370401,484.793987,3.548270e+06,7.309928e+06,3.548185e+06,7.309850e+06,3.548353e+06,7.310005e+06
4,Лубно_Li_фортификации.geojson,/Volumes/Lexar/Датасет/005_ЛУБНО/06_Лубно_разм...,Лубно,Li,фортификации,fortifikatsii,Polygon,0,0,5701.103033,277.458269,3.548460e+06,7.309688e+06,3.548420e+06,7.309641e+06,3.548499e+06,7.309738e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3255,Постройки_4_SpOr_архитектуры.geojson,/Volumes/Lexar/Датасет/153_Постройки_4/06_Пос...,Постройки_4,SpOr,архитектуры,arkhitektury,Polygon,0,0,2059.241880,174.007648,8.588398e+06,5.267756e+06,8.588370e+06,5.267730e+06,8.588424e+06,5.267784e+06
3256,Постройки_5_SpOr_архитектуры.geojson,/Volumes/Lexar/Датасет/154_Постройки_5/06_Пос...,Постройки_5,SpOr,архитектуры,arkhitektury,Polygon,0,0,535.521840,88.701717,8.523140e+06,5.252514e+06,8.523128e+06,5.252499e+06,8.523154e+06,5.252528e+06
3257,Постройки_5_SpOr_архитектуры.geojson,/Volumes/Lexar/Датасет/154_Постройки_5/06_Пос...,Постройки_5,SpOr,архитектуры,arkhitektury,Polygon,1,0,943.612463,196.684189,8.523147e+06,5.252472e+06,8.523129e+06,5.252434e+06,8.523172e+06,5.252500e+06
3258,Постройки_5_SpOr_архитектуры.geojson,/Volumes/Lexar/Датасет/154_Постройки_5/06_Пос...,Постройки_5,SpOr,архитектуры,arkhitektury,Polygon,2,0,65.193050,43.530613,8.523174e+06,5.252451e+06,8.523166e+06,5.252446e+06,8.523184e+06,5.252455e+06
3259,Судбищи_Li_фортификации.geojson,/Volumes/Lexar/Датасет/670_СУДБИЩИ/06_Судбищи_...,Судбищи,Li,фортификации,fortifikatsii,Polygon,0,0,1584.225894,370.061967,4.121489e+05,5.874080e+06,4.121172e+05,5.874055e+06,4.121935e+05,5.874116e+06

In [72]:
df_goal.shape

(3260, 17)

In [73]:
df_goal.groupby("region").size().sort_values(ascending=False)

region
Тимерево            885
Боровичи            194
Изборск             185
Гочево              112
Миловидово_0.1км    109
                   ...
Постройки_2          1
Постройки_4          1
Судбищи               1
Тоссор                1
Шаты                  1
Length: 109, dtype: int64

In [74]:
df_goal["modality"].value_counts()

modality
Ae      1274
SpOr     976
Li       934
Or        76
Name: count, dtype: int64

In [34]:
df_tif = pd.read_csv("/content/tif_registry.csv")

In [35]:
df_tif

,region_folder,region,file_name,file_path,parent_folder,modality,map_type_full,map_type_suffix,exists
0,004_ДЕМИДОВКА,ДЕМИДОВКА,01_Демидовка_Li_карты_с.tif,/Volumes/Lexar/Датасет/004_ДЕМИДОВКА/02_Демидо...,/Volumes/Lexar/Датасет/004_ДЕМИДОВКА/02_Демидо...,Li,Демидовка_Li_карты_с,NaN,True
1,004_ДЕМИДОВКА,ДЕМИДОВКА,02_Демидовка_Li_карты_ch.tif,/Volumes/Lexar/Датасет/004_ДЕМИДОВКА/02_Демидо...,/Volumes/Lexar/Датасет/004_ДЕМИДОВКА/02_Демидо...,Li,Демидовка_Li_карты_ch,ch,True
2,004_ДЕМИДОВКА,ДЕМИДОВКА,03_Демидовка_Li_карты_g.tif,/Volumes/Lexar/Датасет/004_ДЕМИДОВКА/02_Демидо...,/Volumes/Lexar/Датасет/004_ДЕМИДОВКА/02_Демидо...,Li,Демидовка_Li_карты_g,g,True
3,004_ДЕМИДОВКА,ДЕМИДОВКА,04_Демидовка_Li_карты_i.tif,/Volumes/Lexar/Датасет/004_ДЕМИДОВКА/02_Демидо...,/Volumes/Lexar/Датасет/004_ДЕМИДОВКА/02_Демидо...,Li,Демидовка_Li_карты_i,i,True
4,005_ЛУБНО,ЛУБНО,01_Лубно_Li_карты_c.tif,/Volumes/Lexar/Датасет/005_ЛУБНО/02_Лубно_Li_к...,/Volumes/Lexar/Датасет/005_ЛУБНО/02_Лубно_Li_к...,Li,Лубно_Li_карты_c,c,True
...,...,...,...,...,...,...,...,...,...
243,670_СУДБИЩИ,СУДБИЩИ,01_Судбищи_MagGr_серый.tif,/Volumes/Lexar/Датасет/670_СУДБИЩИ/07_Судбищи_...,/Volumes/Lexar/Датасет/670_СУДБИЩИ/07_Судбищи_...,MagGr,Судбищи_MagGr_серый,NaN,True
244,670_СУДБИЩИ,СУДБИЩИ,Судбищи_MagGr_цвет.tif,/Volumes/Lexar/Датасет/670_СУДБИЩИ/extra/Судби...,/Volumes/Lexar/Датасет/670_СУДБИЩИ/extra,MagGr,Судбищи_MagGr_цвет,NaN,True
245,683_Семибратнее_Городище_уч1,Семибратнее,01_Семибратнее_Городище_уч1_MagGr_серый.tif,/Volumes/Lexar/Датасет/683_Семибратнее_Городищ...,/Volumes/Lexar/Датасет/683_Семибратнее_Городищ...,MagGr,Семибратнее_Городище_уч1_MagGr_серый,NaN,True
246,684_Семибратнее_Городище_уч2,Семибратнее,01_Семибратнее_Городище_уч2_MagGr_серый.tif,/Volumes/Lexar/Датасет/684_Семибратнее_Городищ...,/Volumes/Lexar/Датасет/684_Семибратнее_Городищ...,MagGr,Семибратнее_Городище_уч2_MagGr_серый,NaN,True
247,685_Семибратнее_Городище_уч3,Семибратнее,01_Семибратнее_Городище_уч3._MagGr_серый.tif,/Volumes/Lexar/Датасет/685_Семибратнее_Городищ...,/Volumes/Lexar/Датасет/685_Семибратнее_Городищ...,MagGr,Семибратнее_Городище_уч3._MagGr_серый,NaN,True

In [25]:
print("Всего регионов:", len(df))
print("Есть geojson:", df["has_geojson"].sum())
print("Есть LiDAR:", df["has_lidar_tif"].sum())
print("Есть Ae:", df["has_ae_tif"].sum())

Всего регионов: 112
Есть geojson: 112
Есть LiDAR: 33
Есть Ae: 16

In [ ]:
print("Всего регионов:", len(df))
print("Валидных:", df["valid"].sum())
print()

print(df["valid"].value_counts())

# без lidar
print("\n Нет LiDAR:")
print(df[~df["has_lidar_tif"]]["region"].tolist())

# без разметки
print("\n Нет разметки:")
print(df[~df["has_geojson"]]["region"].tolist())

# странные случаи
print("\n Мало tif (<4):")
print(df[(df["num_lidar_tif"] < 4) & df["has_lidar_tif"]][["region", "num_lidar_tif"]])

class_counts = {}

for region in root.iterdir():
    if not region.is_dir():
        continue

    for sub in region.iterdir():
        if "разметка" in sub.name.lower():
            for f in sub.glob("*.geojson"):
                cls = f.stem.split("_")[-1]

                class_counts[cls] = class_counts.get(cls, 0) + 1

print("\nКлассы:")
for k, v in sorted(class_counts.items(), key=lambda x: -x[1]):
    print(f"{k}: {v}")